// Mesh exporters: binary PLY, Wavefront OBJ and glTF binary (GLB).

/** @param mesh {positions: Float32Array, normals?: Float32Array, colors?: Float32Array (0..1), indices: Uint32Array} */
export function toPLY(mesh) {
  const n = mesh.positions.length / 3, nf = mesh.indices.length / 3;
  const hasN = !!mesh.normals, hasC = !!mesh.colors;
  let header = `ply\nformat binary_little_endian 1.0\ncomment Generated by Phonogeometry\nelement vertex ${n}\nproperty float x\nproperty float y\nproperty float z\n`;
  if (hasN) header += 'property float nx\nproperty float ny\nproperty float nz\n';
  if (hasC) header += 'property uchar red\nproperty uchar green\nproperty uchar blue\n';
  header += `element face ${nf}\nproperty list uchar int vertex_indices\nend_header\n`;
  const headerBytes = new TextEncoder().encode(header);
  const vSize = 12 + (hasN ? 12 : 0) + (hasC ? 3 : 0);
  const buf = new ArrayBuffer(headerBytes.length + n * vSize + nf * 13);
  const u8 = new Uint8Array(buf);
  u8.set(headerBytes, 0);
  const dv = new DataView(buf);
  let o = headerBytes.length;
  for (let i = 0; i < n; i++) {
    dv.setFloat32(o, mesh.positions[i * 3], true); dv.setFloat32(o + 4, mesh.positions[i * 3 + 1], true); dv.setFloat32(o + 8, mesh.positions[i * 3 + 2], true); o += 12;
    if (hasN) { dv.setFloat32(o, mesh.normals[i * 3], true); dv.setFloat32(o + 4, mesh.normals[i * 3 + 1], true); dv.setFloat32(o + 8, mesh.normals[i * 3 + 2], true); o += 12; }
    if (hasC) { u8[o] = Math.round(mesh.colors[i * 3] * 255); u8[o + 1] = Math.round(mesh.colors[i * 3 + 1] * 255); u8[o + 2] = Math.round(mesh.colors[i * 3 + 2] * 255); o += 3; }
  }
  for (let i = 0; i < nf; i++) {
    u8[o] = 3; dv.setInt32(o + 1, mesh.indices[i * 3], true); dv.setInt32(o + 5, mesh.indices[i * 3 + 1], true); dv.setInt32(o + 9, mesh.indices[i * 3 + 2], true); o += 13;
  }
  return buf;
}

export function toOBJ(mesh) {
  const n = mesh.positions.length / 3;
  const lines = ['# Generated by Phonogeometry'];
  for (let i = 0; i < n; i++) {
    let l = `v ${mesh.positions[i * 3].toFixed(5)} ${mesh.positions[i * 3 + 1].toFixed(5)} ${mesh.positions[i * 3 + 2].toFixed(5)}`;
    if (mesh.colors) l += ` ${mesh.colors[i * 3].toFixed(3)} ${mesh.colors[i * 3 + 1].toFixed(3)} ${mesh.colors[i * 3 + 2].toFixed(3)}`;
    lines.push(l);
  }
  if (mesh.normals) for (let i = 0; i < n; i++) lines.push(`vn ${mesh.normals[i * 3].toFixed(4)} ${mesh.normals[i * 3 + 1].toFixed(4)} ${mesh.normals[i * 3 + 2].toFixed(4)}`);
  for (let i = 0; i < mesh.indices.length; i += 3) {
    const a = mesh.indices[i] + 1, b = mesh.indices[i + 1] + 1, c = mesh.indices[i + 2] + 1;
    lines.push(mesh.normals ? `f ${a}//${a} ${b}//${b} ${c}//${c}` : `f ${a} ${b} ${c}`);
  }
  return lines.join('\n') + '\n';
}

function pad4(n) { return (n + 3) & ~3; }

/** glTF 2.0 binary with POSITION, optional NORMAL and COLOR_0, uint32 indices. */
export function toGLB(mesh) {
  const n = mesh.positions.length / 3;
  const chunks = [];
  const bufferViews = [], accessors = [];
  let offset = 0;
  const addView = (typed, target, componentType, type, count, minmax) => {
    const bytes = new Uint8Array(typed.buffer, typed.byteOffset, typed.byteLength);
    chunks.push(bytes);
    bufferViews.push({ buffer: 0, byteOffset: offset, byteLength: bytes.byteLength, ...(target ? { target } : {}) });
    const acc = { bufferView: bufferViews.length - 1, componentType, count, type };
    if (minmax) Object.assign(acc, minmax);
    accessors.push(acc);
    offset += pad4(bytes.byteLength);
    return accessors.length - 1;
  };
  const min = [Infinity, Infinity, Infinity], max = [-Infinity, -Infinity, -Infinity];
  for (let i = 0; i < n; i++) for (let k = 0; k < 3; k++) {
    const v = mesh.positions[i * 3 + k];
    if (v < min[k]) min[k] = v;
    if (v > max[k]) max[k] = v;
  }
  const attributes = { POSITION: addView(mesh.positions, 34962, 5126, 'VEC3', n, { min, max }) };
  if (mesh.normals) attributes.NORMAL = addView(mesh.normals, 34962, 5126, 'VEC3', n);
  if (mesh.colors) attributes.COLOR_0 = addView(mesh.colors, 34962, 5126, 'VEC3', n);
  const indicesAcc = addView(mesh.indices, 34963, 5125, 'SCALAR', mesh.indices.length);
  const json = {
    asset: { version: '2.0', generator: 'Phonogeometry' },
    scene: 0,
    scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0, name: 'scan' }],
    meshes: [{ primitives: [{ attributes, indices: indicesAcc, mode: 4, material: 0 }] }],
    materials: [{ pbrMetallicRoughness: { baseColorFactor: [1, 1, 1, 1], metallicFactor: 0, roughnessFactor: 0.9 }, doubleSided: true }],
    buffers: [{ byteLength: offset }],
    bufferViews,
    accessors,
  };
  let jsonBytes = new TextEncoder().encode(JSON.stringify(json));
  const jsonPadded = new Uint8Array(pad4(jsonBytes.length)).fill(0x20);
  jsonPadded.set(jsonBytes);
  const total = 12 + 8 + jsonPadded.length + 8 + offset;
  const out = new ArrayBuffer(total);
  const dv = new DataView(out), u8 = new Uint8Array(out);
  dv.setUint32(0, 0x46546c67, true); dv.setUint32(4, 2, true); dv.setUint32(8, total, true);
  dv.setUint32(12, jsonPadded.length, true); dv.setUint32(16, 0x4e4f534a, true);
  u8.set(jsonPadded, 20);
  let o = 20 + jsonPadded.length;
  dv.setUint32(o, offset, true); dv.setUint32(o + 4, 0x004e4942, true); o += 8;
  for (const c of chunks) { u8.set(c, o); o += pad4(c.byteLength); }
  return out;
}
